name: Daily Scrape
on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser supabase openai
      - name: Run Scraper
        run: python scrape_news.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
